### ISSUE TITLE
report-view issue: ValueError: path is on mount 'C:', start on mount 'E:'

### ISSUE THREAD

**Issue by yangzetao** [NASA-SW-VnV/ikos#165]
Error when executing " rel_path = os.path.relpath(os.path.realpath(path), os.getcwd())" for report-view command.
I printed the relpath parameters:
1) relpath first parameter:  **C:/data/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h**
2) relpath second parameter: **E:/data**

OS: Windows 10
ikos: 3.0
Python: 3.8.5 (MSYS2)

Exception happened during processing of request from ('127.0.0.1', 56808)
Traceback (most recent call last):
  File "C:/data/msys64/mingw64/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:/data/msys64/mingw64/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:/data/msys64/mingw64/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:/data/msys64/mingw64/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "C:/data/msys64/mingw64/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "C:/data/msys64/mingw64/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "C:/data/ikos/lib/python3.8/site-packages/ikos/view.py", line 146, in do_GET
    f(**m.groupdict())
  File "C:/data/ikos/lib/python3.8/site-packages/ikos/view.py", line 170, in _serve_homepage
    'files': json.dumps(self._files()),
  File "C:/data/ikos/lib/python3.8/site-packages/ikos/view.py", line 206, in _files
    'path': report.format_path(file.path),
  File "C:/data/ikos/lib/python3.8/site-packages/ikos/report.py", line 277, in helper
    cache[args] = f(*args)
  File "C:/data/ikos/lib/python3.8/site-packages/ikos/report.py", line 294, in format_path
    rel_path = os.path.relpath(os.path.realpath(path), os.getcwd())
  File "C:/data/msys64/mingw64/lib/python3.8/ntpath.py", line 716, in relpath
    raise ValueError("path is on mount %r, start on mount %r, %s, \t%s" % (
**ValueError: path is on mount 'C:', start on mount 'E:'**, C:/data/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h,  E:/data

**Comment by ivanperez-keera** [comment]
That exception is happening because we are trying to obtain the relative path of a file wrt the current working directory and they may be in different units on Windows.

I believe something like the following could protect that call to make sure it doesn't throw an exception:

```python
@memoize
def format_path(path):
    '''
    Format a path.

    Return the shortest between the absolute path or the relative path.
    '''
    if not path:
        return None

    abs_path = os.path.realpath(path)
    
    # Check the drives to make sure a relpath can be obtained 
    path_drive_split = os.path.splitdrive(abs_path)
    cur_drive_split  = os.path.splitdrive(os.getcwd())

    if path_drive_split and (path_drive_split[0] != cur_drive_split[0]):
        return abs_path
    else:
        rel_path = os.path.relpath(os.path.realpath(path), os.getcwd())
        return min(abs_path, rel_path, key=len)
```

On linux the function `splitdrive` returns the empty string, so the condition will be false and the if-then-else will execute the prior behavior.

@arthaud This is my first (potential) contribution to ikos. Does this roughly look like a possible solution or am I too far off?

**Comment by arthaud** [comment]
That looks fine to me, feel free to submit a PR.
