### ISSUE TITLE
analyzer.py uses threading.Thread.isAlive(), which was removed in Python 3.9

### ISSUE THREAD

**Issue by dgunay** [NASA-SW-VnV/ikos#167]
Per https://bugs.python.org/issue37804, `Thread.isAlive()` was removed in Python 3.9 in favor of Thread.is_alive(). `ikos` crashes on my system because of this. 

```
Traceback (most recent call last):
  File "/usr/local/bin/ikos", line 65, in <module>
    ikos.analyzer.main(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/ikos/analyzer.py", line 1018, in main
    ikos_analyzer(opt.output_db, pp_path, opt)
  File "/usr/local/lib/python3.9/site-packages/ikos/analyzer.py", line 912, in ikos_analyzer
    if timer.isAlive():
AttributeError: 'Timer' object has no attribute 'isAlive'
```

Changing the offending line to use `is_alive()` fixes the issue.

**Comment by dgunay** [comment]
Closing after the merging of https://github.com/NASA-SW-VnV/ikos/pull/168
