### ISSUE TITLE
Broken on system with python 3.13 - no module named 'pipes'

### ISSUE THREAD

**Issue by mickyabir** [NASA-SW-VnV/ikos#292]
I tried installing ikos using homebrew on MacOS Sonoma (M3 MBP) and after installing and trying to run ikos, I got:

`error: could not find ikos python module
error: see TROUBLESHOOTING.md`

Upon further investigation, I found the root problem:

`Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ikos
>>> import ikos.analyzer
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    import ikos.analyzer
  File "/opt/homebrew/Cellar/ikos/3.4_1/libexec/lib/python3.13/site-packages/ikos/analyzer.py", line 48, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'`

Apparently this module has been removed in python3 3.13 (https://docs.python.org/3/whatsnew/3.13.html)

**Comment by ivanperez-keera** [comment]
Thanks for reporting this, @mickyabir .

I could be wrong but it's possible that `pipes` is only needed for this:

https://github.com/NASA-SW-VnV/ikos/blob/026c409e4ecbc068eaf69f52e6dd230f9e515bcc/analyzer/python/ikos/analyzer.py#L556-L559

The documentation of `subprocess`, which is suggested in Python3 as an alternative to `pipes`, doesn't provide an alternative other than `shlex.quote()`.

If this is a protection to make ikos compatible with older versions of Python, I think it's not needed: since we are already requiring Python >= 3.3 (as per #243, part of IKOS 3.2), I think it's safe to assume that `shlex.quote` is available.

@arthaud Does removing that use of `pipes.quote()` and unconditionally using `shlex.quote()` sound right to you?

**Comment by arthaud** [comment]
Yeah, I think we don't need this anymore. Feel free to submit a PR!

**Comment by ivanperez-keera** [comment]
Micky, if you want, it'd be great to have you contribute the change to IKOS :)

Would you like to submit a PR to remove the import of `pipes` and turn that if-then-else into an unconditional `sh_quote = shlex.quote`. It should be a very small patch.

FYI, we'll ask that you sign one of the two CLAs: https://github.com/NASA-SW-VnV/ikos/tree/master/doc/contribute and send it to [ikos@lists.nasa.gov](mailto:ikos@lists.nasa.gov), CC-ing [ivan.perezdominguez@nasa.gov](mailto:ivan.perezdominguez@nasa.gov). I hate to do this for such a small change, but I have to, especially because we are in the process of changing licenses (to one that will be more permissive).

**Comment by tarikgta2** [comment]
Hello everyone,

I’ve just encountered the same issue while using Python 3.13, and I noticed that a related issue has already been opened. I’ve fixed the problem in the "analyzer.py" file and tested it, and everything is now working smoothly.

I’ve submitted a pull request, but if you'd prefer the original reporter of the issue to handle it and/or to give them credit, I completely understand.

I wish everyone a nice weekend!

tarikgta2

**Comment by Vivraan** [comment]
> Hello everyone,
> 
> I’ve just encountered the same issue while using Python 3.13, and I noticed that a related issue has already been opened. I’ve fixed the problem in the "analyzer.py" file and tested it, and everything is now working smoothly.
> 
> I’ve submitted a pull request, but if you'd prefer the original reporter of the issue to handle it and/or to give them credit, I completely understand.
> 
> I wish everyone a nice weekend!
> 
> tarikgta2

Bumping, and referring #293 here!
