### ISSUE TITLE
ikos crashes when filename or path to file contain non-ASCII characters

### ISSUE THREAD

**Issue by mvforell** [NASA-SW-VnV/ikos#86]
Running `ikos loop.c` (the loop.c from the README) inside a directory with non-ASCII characters in its name (in this case "täst") produces the following error:

	[*] Compiling loop.c
	[*] Running ikos preprocessor
	[*] Running ikos analyzer
	[*] Translating LLVM bitcode to AR
	[*] Running liveness analysis
	[*] Running fixpoint profile analysis
	[*] Running interprocedural value analysis
	[*] Analyzing entry point: main
	[*] Checking properties and writing results for entry point: main

	# Time stats:
	clang        : 0.045 sec
	ikos-analyzer: 0.007 sec
	ikos-pp      : 0.005 sec

	# Summary:
	Total number of checks                : 7
	Total number of unreachable checks    : 0
	Total number of safe checks           : 5
	Total number of definite unsafe checks: 2
	Total number of warnings              : 0

	The program is definitely UNSAFE

	# Results
	/usr/lib/python2.7/genericpath.py:79: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	  s1 = min(m)
	Traceback (most recent call last):
	  File "/home/max/ikos-install/bin/ikos", line 65, in <module>
		ikos.analyzer.main(sys.argv)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/analyzer.py", line 954, in main
		formatter.format(rep)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/report.py", line 940, in format
		super(AutoFormatter, self).format(report)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/report.py", line 752, in format
		self.write_path(function.file())
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/report.py", line 645, in write_path
		printf(bold('%s: '), format_path(file.path) if file else '?',
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/report.py", line 277, in helper
		cache[args] = f(*args)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/report.py", line 294, in format_path
		rel_path = os.path.relpath(os.path.realpath(path), os.getcwd())
	  File "/usr/lib/python2.7/posixpath.py", line 434, in relpath
		i = len(commonprefix([start_list, path_list]))
	  File "/usr/lib/python2.7/genericpath.py", line 79, in commonprefix
		s1 = min(m)
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

This error persists if any directory name (not just the one of the directory which directöy contains loop.c) in the path to the file contains non-ASCII characters.

Also, running `ikos lööp.c` in a directory named "test" (non-ASCII characters in the file name instead of directory name) produces this error:

	[*] Compiling lööp.c
	[*] Running ikos preprocessor
	[*] Running ikos analyzer
	[*] Translating LLVM bitcode to AR
	[*] Running liveness analysis
	[*] Running fixpoint profile analysis
	[*] Running interprocedural value analysis
	[*] Analyzing entry point: main
	[*] Checking properties and writing results for entry point: main
	Traceback (most recent call last):
	  File "/home/max/ikos-install/bin/ikos", line 65, in <module>
		ikos.analyzer.main(sys.argv)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/analyzer.py", line 905, in main
		db.insert_settings(settings_rows)
	  File "/home/max/ikos-install/lib/python2.7/site-packages/ikos/output_db.py", line 90, in insert_settings
		c.executemany('INSERT INTO settings VALUES (?, ?)', rows)
	sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by arthaud** [comment]
Thanks for the bug report. This is fixed in 8b4e09cfdb127c0ba2ff16ffc188160a2d9e14fa.
